import assert from "node:assert/strict";
import test from "node:test";
import Database from "better-sqlite3";
import { ResearchQueueRepository } from "../src/repositories/researchQueueRepository.js";
import { ResearchQueueService } from "../src/services/research-queue.js";
import type { ResearchQueueEntry } from "../src/types/research-queue.js";

function setup() { const db = new Database(":memory:"); const repo = new ResearchQueueRepository(db); return { db, repo, service: new ResearchQueueService(repo) }; }

test("adds idempotently with defaults and preserves original values", () => { const { db, service } = setup(); const first = service.add("TokenA", undefined, undefined, "seed"); const second = service.add("TokenA", "ARCHIVED", "HIGH", "changed"); assert.ok(first.ok && second.ok); assert.equal((first.data as ResearchQueueEntry).status, "DISCOVERED"); assert.equal((second.data as ResearchQueueEntry).reason, "seed"); assert.equal((second.data as ResearchQueueEntry).status, "DISCOVERED"); assert.equal((second.data as ResearchQueueEntry).priority, "MEDIUM"); db.close(); });
test("updates and archives existing entries, while missing updates are typed", () => { const { db, service } = setup(); assert.equal(service.updateStatus("none", "SCREENED").ok, false); service.add("TokenA"); const updated = service.updateStatus("TokenA", "WATCHING"); assert.ok(updated.ok && (updated.data as ResearchQueueEntry).status === "WATCHING"); const archived = service.archive("TokenA"); assert.ok(archived.ok && (archived.data as ResearchQueueEntry).status === "ARCHIVED"); db.close(); });
test("filters and orders priority explicitly, with updated_at tie-break", () => { const { db, repo, service } = setup(); repo.add("low", "DISCOVERED", "LOW", null, 1); repo.add("high", "DISCOVERED", "HIGH", null, 1); repo.add("medium", "DISCOVERED", "MEDIUM", null, 1); repo.updatePriority("high", "HIGH", 3); repo.updatePriority("medium", "MEDIUM", 2); const listed = service.list(); assert.ok(listed.ok); assert.deepEqual((listed.data as ResearchQueueEntry[]).map((entry) => entry.tokenAddress), ["high", "medium", "low"]); const filtered = service.list("DISCOVERED", "MEDIUM"); assert.ok(filtered.ok && (filtered.data as ResearchQueueEntry[]).length === 1); db.close(); });
test("orders same-priority entries by updated_at descending", () => { const { db, repo, service } = setup(); repo.add("older", "DISCOVERED", "HIGH", null, 10); repo.add("newer", "DISCOVERED", "HIGH", null, 20); const listed = service.list(); assert.ok(listed.ok); assert.deepEqual((listed.data as ResearchQueueEntry[]).slice(0, 2).map((entry) => entry.tokenAddress), ["newer", "older"]); db.close(); });
test("archive changes only research queue", () => { const db = new Database(":memory:"); db.exec("CREATE TABLE watchlist_entries (token_address TEXT PRIMARY KEY, added_at INTEGER NOT NULL, reason TEXT); CREATE TABLE token_snapshots (id INTEGER PRIMARY KEY, token_address TEXT, captured_at INTEGER); INSERT INTO watchlist_entries VALUES ('TokenA',1,'keep'); INSERT INTO token_snapshots VALUES (1,'TokenA',2);"); const repo = new ResearchQueueRepository(db); const service = new ResearchQueueService(repo); service.add("TokenA"); service.archive("TokenA"); assert.equal((db.prepare("SELECT reason FROM watchlist_entries WHERE token_address='TokenA'").get() as { reason: string }).reason, "keep"); assert.equal((db.prepare("SELECT count(*) count FROM token_snapshots").get() as { count: number }).count, 1); db.close(); });
